name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24]

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm format:check
      - run: pnpm build
      - run: pnpm typecheck

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24]

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: build
        run: pnpm build

  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24]

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: run unit tests
        run: pnpm test

  storybook-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: install playwright chromium
        run: pnpm --filter terra-draw-cesium-adapter-storybook exec playwright install chromium --with-deps
      - name: run storybook tests
        run: pnpm test:storybook
